version: '3.8'
services:
  frontend:
    build: ./client
    container_name: react-app
    tty: true
    stdin_open: true
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - /app/node_modules
